/*
 * sequence_alignment_test.h
 *
 *  Created on: Feb 15, 2016
 *      Author: isovic
 */

#ifndef CODEBASE_SEQLIB_SRC_SEQUENCES_SEQUENCE_TEST_H_
#define CODEBASE_SEQLIB_SRC_SEQUENCES_SEQUENCE_TEST_H_

void TEST_CLASS_SEQUENCE_ALIGNMENT();

#endif /* CODEBASE_SEQLIB_SRC_SEQUENCES_SEQUENCE_TEST_H_ */
